direction: left

**: {
  style.font-size: 100

  style.font-color: "#fffafa"
}

body*: {width: 3400}
grid*: {width: 3400}

boorder: "" {
body: "الكلام"
grid: "" {
  grid-columns: 1

  اللفظ \: صوت مشتمل على حروف الهجاء  :{width: 3300}
  المركب \: مؤلف من كلمتين أو أكثر تحقيقا أو تقديرا
  المفيد \: يحسن سكوت المتكلم عليه ويحصل منه الفائدة
  بالوضع  \: لفظ وضعه العرب للدلالة على معنى من المعاني
}

body1: "أنواع الكلام"
grid1: "" {
  grid-columns: 1

  اسم \: كلمة دلت على معنى في نفسها ولم تقترن بزمان: {width: 3300}
  فعل \: كلمة دلت على معنى في نفسها واقترنت بزمان
  حرف \: كلمة لا تدل على معنى في نفسها وتدل على معنى في غيرها
}

body2: "علامات الاسم"
grid2: "" {
  grid-columns: 1

  الإسناد إليه - كتبت بالقلم  ( التاء فاعل و مسند اليها الكتابة ): {width: 3300}
  الخفض - رأيت كتاب الطالبِ ( طالب اسم لأنه مخفوض )
  حروف الخفض - عدت إلى المنزلِ ( منزل اسم لأنه سبق بحرف خفض )
  التنوين - هذا طالبٌ مجتهدٌ ( طالب و مجتهد اسمان لأنهما منونان )
  دخول الألف واللام - كتبت على الطاولة ( طاولة اسم لدخول أل عليها )
}

body3: "علامات الفعل"
grid3: "" {
  grid-columns: 1

  قد - قد أفلح المؤمنون  ( أفلح فعل لدخول قد عليه ) : {width: 3300}
  السين - سأستغفر لك ربي ( أستغفر فعل لأنه سبق بالسين)
  سوف - سوف أقوم بواجبي ( أقوم فعل لأنه سبق بسوف)
  تاء التأنيث الساكنة - جائت سندس ( جاء فعل لدخول التاء عليه)
}

body4: "علامة الحرف"
grid4: "" {
  grid-columns: 1
  ما لا يصلح معه دليل الاسم ولا دليل الفعل: {width: 3300}
}

body5: "أنواع الأفعال وعلاماتها"
grid5: "" {
  grid-columns: 1
  ماضي: {width: 3300; style.fill: "#45475A"}
  تاء  التأنيث الساكنة
  مضارع :{style.fill: "#45475A"}
  قبوله الجزم بـ لم
  يبدأ بأحد حروف أنيت
  يضم أوله إذا كان ماضيه من أربعة حروف
  يفتح أوله فيما عدا ذلك

  أمر :{style.fill: "#45475A"}
  يدل على الطلب
  دخول ياء المخاطبة
}

}
# N1: "#CDD6F4",
# N2: "#BAC2DE",
# N3: "#A6ADC8",
# N4: "#585B70",
# N5: "#45475A",
# N6: "#45475A",
# N7: "#1E1E2E",


vars: {
    d2-config: {
      theme-overrides: {

        # B2: "#66BB6A"
        # B3: "#A5D6A7"
        # B4: "#45475A"

      }
    }
  }